from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSlider, QSpinBox, QStatusBar, QWidget)

class Ui_SearchWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(380, 351)
        MainWindow.setMinimumSize(QSize(380, 351))
        MainWindow.setMaximumSize(QSize(380, 351))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 221, 31))
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 50, 361, 231))
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 51, 16))
        self.SearchBar = QLineEdit(self.widget)
        self.SearchBar.setObjectName(u"SearchBar")
        self.SearchBar.setGeometry(QRect(60, 10, 291, 22))
        self.minSlider = QSlider(self.widget)
        self.minSlider.setObjectName(u"minSlider")
        self.minSlider.setGeometry(QRect(100, 40, 160, 22))
        self.minSlider.setMaximum(1000)
        self.minSlider.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 40, 81, 16))
        self.minSpin = QSpinBox(self.widget)
        self.minSpin.setObjectName(u"minSpin")
        self.minSpin.setGeometry(QRect(270, 40, 81, 22))
        self.minSpin.setMaximum(1000)
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 80, 81, 16))
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 71, 16))
        self.maxSlider = QSlider(self.widget)
        self.maxSlider.setObjectName(u"maxSlider")
        self.maxSlider.setGeometry(QRect(100, 80, 160, 22))
        self.maxSlider.setMaximum(1000)
        self.maxSlider.setOrientation(Qt.Horizontal)
        self.maxSpin = QSpinBox(self.widget)
        self.maxSpin.setObjectName(u"maxSpin")
        self.maxSpin.setGeometry(QRect(270, 80, 81, 22))
        self.maxSpin.setMaximum(1000)
        self.playerSpin = QSpinBox(self.widget)
        self.playerSpin.setObjectName(u"playerSpin")
        self.playerSpin.setGeometry(QRect(90, 110, 71, 22))
        self.playerSpin.setMaximum(100)
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 110, 81, 16))
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(170, 110, 181, 111))
        self.label_7 = QLabel(self.widget_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 81, 16))
        self.thematicBox = QCheckBox(self.widget_2)
        self.thematicBox.setObjectName(u"thematicBox")
        self.thematicBox.setGeometry(QRect(10, 20, 75, 20))
        self.warBox = QCheckBox(self.widget_2)
        self.warBox.setObjectName(u"warBox")
        self.warBox.setGeometry(QRect(10, 60, 75, 20))
        self.strategyBox = QCheckBox(self.widget_2)
        self.strategyBox.setObjectName(u"strategyBox")
        self.strategyBox.setGeometry(QRect(10, 40, 75, 20))
        self.CGSBox = QCheckBox(self.widget_2)
        self.CGSBox.setObjectName(u"CGSBox")
        self.CGSBox.setGeometry(QRect(10, 80, 75, 20))
        self.familyBox = QCheckBox(self.widget_2)
        self.familyBox.setObjectName(u"familyBox")
        self.familyBox.setGeometry(QRect(100, 20, 75, 20))
        self.abstractBox = QCheckBox(self.widget_2)
        self.abstractBox.setObjectName(u"abstractBox")
        self.abstractBox.setGeometry(QRect(100, 40, 75, 20))
        self.partyBox = QCheckBox(self.widget_2)
        self.partyBox.setObjectName(u"partyBox")
        self.partyBox.setGeometry(QRect(100, 60, 75, 20))
        self.childBox = QCheckBox(self.widget_2)
        self.childBox.setObjectName(u"childBox")
        self.childBox.setGeometry(QRect(100, 80, 75, 20))
        self.comboSort = QComboBox(self.widget)
        self.comboSort.addItem("")
        self.comboSort.addItem("")
        self.comboSort.addItem("")
        self.comboSort.setObjectName(u"comboSort")
        self.comboSort.setGeometry(QRect(10, 180, 151, 22))
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 160, 81, 16))
        self.searchButton = QPushButton(self.centralwidget)
        self.searchButton.setObjectName(u"searchButton")
        self.searchButton.setGeometry(QRect(310, 290, 61, 24))
        self.exitButton = QPushButton(self.centralwidget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(10, 290, 51, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.minSlider.valueChanged.connect(self.minSpin.setValue)
        self.minSpin.valueChanged.connect(self.minSlider.setValue)
        self.maxSlider.valueChanged.connect(self.maxSpin.setValue)
        self.maxSpin.valueChanged.connect(self.maxSlider.setValue)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Search For Games</span></p></body></html>", None))
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Leave blank to search all games", None))
#endif // QT_CONFIG(statustip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Search:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.SearchBar.setToolTip(QCoreApplication.translate("MainWindow", u"Leave blank for no query", None))
#endif // QT_CONFIG(tooltip)
        self.SearchBar.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search for a board game...", None))
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for no min", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_3.setStatusTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for no min", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Min Playtime:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for no max", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_4.setStatusTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for no max", None))
#endif // QT_CONFIG(statustip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Max Playtime:</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"(In minutes)", None))
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for any playercount", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_6.setStatusTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for any playercount", None))
#endif // QT_CONFIG(statustip)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Playercount:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip(QCoreApplication.translate("MainWindow", u"Selecting more than 2 can lead to no results", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_7.setStatusTip(QCoreApplication.translate("MainWindow", u"Selecting more than 2 can lead to no results", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_7.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Catagories:</span></p></body></html>", None))
        self.thematicBox.setText(QCoreApplication.translate("MainWindow", u"Thematic", None))
        self.warBox.setText(QCoreApplication.translate("MainWindow", u"War", None))
        self.strategyBox.setText(QCoreApplication.translate("MainWindow", u"Strategy", None))
#if QT_CONFIG(tooltip)
        self.CGSBox.setToolTip(QCoreApplication.translate("MainWindow", u"Card Games", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.CGSBox.setStatusTip(QCoreApplication.translate("MainWindow", u"Card Games", None))
#endif // QT_CONFIG(statustip)
        self.CGSBox.setText(QCoreApplication.translate("MainWindow", u"CGS", None))
        self.familyBox.setText(QCoreApplication.translate("MainWindow", u"Family", None))
        self.abstractBox.setText(QCoreApplication.translate("MainWindow", u"Abstract", None))
        self.partyBox.setText(QCoreApplication.translate("MainWindow", u"Party", None))
        self.childBox.setText(QCoreApplication.translate("MainWindow", u"Childrens", None))
        self.comboSort.setItemText(0, QCoreApplication.translate("MainWindow", u"Rank", None))
        self.comboSort.setItemText(1, QCoreApplication.translate("MainWindow", u"# of Owners", None))
        self.comboSort.setItemText(2, QCoreApplication.translate("MainWindow", u"BGG ID", None))

#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(QCoreApplication.translate("MainWindow", u"Leave at 0 for any playercount", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(QCoreApplication.translate("MainWindow", u"What results come up first", None))
#endif // QT_CONFIG(statustip)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Sort By:</span></p></body></html>", None))
#if QT_CONFIG(statustip)
        self.searchButton.setStatusTip(QCoreApplication.translate("MainWindow", u"Search with selected settings", None))
#endif // QT_CONFIG(statustip)
        self.searchButton.setText(QCoreApplication.translate("MainWindow", u"Search", None))
#if QT_CONFIG(statustip)
        self.exitButton.setStatusTip(QCoreApplication.translate("MainWindow", u"Back to homepage", None))
#endif // QT_CONFIG(statustip)
        self.exitButton.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
    # retranslateUi
