from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QStatusBar, QTabWidget, QWidget)

class Ui_SettingsWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(289, 284)
        MainWindow.setMinimumSize(QSize(289, 284))
        MainWindow.setMaximumSize(QSize(289, 284))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(271, 211))
        self.tabWidget.setMaximumSize(QSize(271, 211))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.labelUsername = QLabel(self.tab)
        self.labelUsername.setObjectName(u"labelUsername")
        self.labelUsername.setGeometry(QRect(10, 10, 201, 24))
        self.labelUsername.setWordWrap(False)
        self.labelNickname = QLabel(self.tab)
        self.labelNickname.setObjectName(u"labelNickname")
        self.labelNickname.setGeometry(QRect(10, 40, 201, 24))
        self.labelPassword = QLabel(self.tab)
        self.labelPassword.setObjectName(u"labelPassword")
        self.labelPassword.setGeometry(QRect(10, 70, 161, 24))
        self.buttonDelete = QPushButton(self.tab)
        self.buttonDelete.setObjectName(u"buttonDelete")
        self.buttonDelete.setGeometry(QRect(150, 150, 111, 24))
        self.buttonDelete.setMinimumSize(QSize(111, 24))
        self.buttonDelete.setMaximumSize(QSize(111, 24))
        self.buttonPassEdit = QPushButton(self.tab)
        self.buttonPassEdit.setObjectName(u"buttonPassEdit")
        self.buttonPassEdit.setGeometry(QRect(220, 70, 41, 24))
        self.buttonPassEdit.setMinimumSize(QSize(41, 24))
        self.buttonPassEdit.setMaximumSize(QSize(41, 24))
        self.buttonPassView = QPushButton(self.tab)
        self.buttonPassView.setObjectName(u"buttonPassView")
        self.buttonPassView.setGeometry(QRect(180, 70, 41, 24))
        self.buttonPassView.setMinimumSize(QSize(41, 24))
        self.buttonPassView.setMaximumSize(QSize(41, 24))
        self.buttonNickEdit = QPushButton(self.tab)
        self.buttonNickEdit.setObjectName(u"buttonNickEdit")
        self.buttonNickEdit.setGeometry(QRect(220, 40, 41, 24))
        self.buttonNickEdit.setMinimumSize(QSize(41, 24))
        self.buttonNickEdit.setMaximumSize(QSize(41, 24))
        self.buttonUserEdit = QPushButton(self.tab)
        self.buttonUserEdit.setObjectName(u"buttonUserEdit")
        self.buttonUserEdit.setGeometry(QRect(220, 10, 41, 24))
        self.buttonUserEdit.setMinimumSize(QSize(41, 24))
        self.buttonUserEdit.setMaximumSize(QSize(41, 24))
        self.buttonUserEdit.setAutoDefault(False)
        self.buttonUserEdit.setFlat(False)
        self.buttonLogout = QPushButton(self.tab)
        self.buttonLogout.setObjectName(u"buttonLogout")
        self.buttonLogout.setGeometry(QRect(10, 150, 61, 24))
        self.buttonLogout.setMinimumSize(QSize(61, 24))
        self.buttonLogout.setMaximumSize(QSize(61, 24))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.labelListNo = QLabel(self.tab_2)
        self.labelListNo.setObjectName(u"labelListNo")
        self.labelListNo.setGeometry(QRect(10, 10, 141, 21))
        self.buttonReset = QPushButton(self.tab_2)
        self.buttonReset.setObjectName(u"buttonReset")
        self.buttonReset.setGeometry(QRect(190, 10, 71, 24))
        self.labelRec = QLabel(self.tab_2)
        self.labelRec.setObjectName(u"labelRec")
        self.labelRec.setGeometry(QRect(10, 40, 111, 16))
        self.frame = QFrame(self.tab_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 60, 181, 51))
        self.frame.setMinimumSize(QSize(181, 51))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)

        self.spinRandom = QSpinBox(self.frame)
        self.spinRandom.setObjectName(u"spinRandom")
        self.spinRandom.setMaximum(100)

        self.gridLayout_2.addWidget(self.spinRandom, 2, 1, 1, 1)

        self.sliderRandom = QSlider(self.frame)
        self.sliderRandom.setObjectName(u"sliderRandom")
        self.sliderRandom.setMaximum(100)
        self.sliderRandom.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.sliderRandom, 2, 0, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.frame_2 = QFrame(self.tab_2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 120, 181, 51))
        self.frame_2.setMinimumSize(QSize(181, 51))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)

        self.spinPriority = QSpinBox(self.frame_2)
        self.spinPriority.setObjectName(u"spinPriority")
        self.spinPriority.setMaximum(100)
        self.spinPriority.setValue(5)

        self.gridLayout_5.addWidget(self.spinPriority, 2, 1, 1, 1)

        self.sliderPriority = QSlider(self.frame_2)
        self.sliderPriority.setObjectName(u"sliderPriority")
        self.sliderPriority.setMaximum(100)
        self.sliderPriority.setValue(5)
        self.sliderPriority.setOrientation(Qt.Horizontal)

        self.gridLayout_5.addWidget(self.sliderPriority, 2, 0, 1, 1)


        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.labelVersion = QLabel(self.tab_3)
        self.labelVersion.setObjectName(u"labelVersion")
        self.labelVersion.setGeometry(QRect(10, 10, 151, 21))
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 151, 21))
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 191, 21))
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 241, 21))
        self.tabWidget.addTab(self.tab_3, "")

        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sliderRandom.valueChanged.connect(self.spinRandom.setValue)
        self.sliderPriority.valueChanged.connect(self.spinPriority.setValue)
        self.spinPriority.valueChanged.connect(self.sliderPriority.setValue)
        self.spinRandom.valueChanged.connect(self.sliderRandom.setValue)

        self.tabWidget.setCurrentIndex(0)
        self.buttonUserEdit.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Settings</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.labelUsername.setToolTip(QCoreApplication.translate("MainWindow", u"Used to login and save user data", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.labelUsername.setStatusTip(QCoreApplication.translate("MainWindow", u"Used to login and save user data", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.labelUsername.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.labelUsername.setText(QCoreApplication.translate("MainWindow", u"Username: None", None))
#if QT_CONFIG(tooltip)
        self.labelNickname.setToolTip(QCoreApplication.translate("MainWindow", u"What the app calls you", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.labelNickname.setStatusTip(QCoreApplication.translate("MainWindow", u"What the app calls you", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.labelNickname.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.labelNickname.setText(QCoreApplication.translate("MainWindow", u"Nickname: None", None))
#if QT_CONFIG(tooltip)
        self.labelPassword.setToolTip(QCoreApplication.translate("MainWindow", u"What the app calls you", None))
#endif // QT_CONFIG(tooltip)
        self.labelPassword.setText(QCoreApplication.translate("MainWindow", u"Password: None", None))
        self.buttonDelete.setText(QCoreApplication.translate("MainWindow", u"Delete Account", None))
        self.buttonPassEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.buttonPassView.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.buttonNickEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.buttonUserEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.buttonLogout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Account", None))
        self.labelListNo.setText(QCoreApplication.translate("MainWindow", u"Games on Wishlist: None", None))
        self.buttonReset.setText(QCoreApplication.translate("MainWindow", u"Reset List", None))
        self.labelRec.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Recommendations:</span></p></body></html>", None))
#if QT_CONFIG(statustip)
        self.label_8.setStatusTip(QCoreApplication.translate("MainWindow", u"Randomness of Recommendations", None))
#endif // QT_CONFIG(statustip)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Random", None))
#if QT_CONFIG(statustip)
        self.sliderRandom.setStatusTip(QCoreApplication.translate("MainWindow", u"Larger = More Random, Default = 0", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.label_9.setStatusTip(QCoreApplication.translate("MainWindow", u"Increases chance of popular recommendations", None))
#endif // QT_CONFIG(statustip)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Popular Game Priority", None))
#if QT_CONFIG(statustip)
        self.sliderPriority.setStatusTip(QCoreApplication.translate("MainWindow", u"Larger = More Popular Games, Default = 5", None))
#endif // QT_CONFIG(statustip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Data Management", None))
        self.labelVersion.setText(QCoreApplication.translate("MainWindow", u"Boardgame Tracker vX.X", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Gabriel Fincham", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Built With: PyQt Designer, Python", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Boardgame Database from Board Game Geek", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

